---

- name: Trash default nginx config
  shell: "mv {{ nginx_config_path }}/default /tmp/"
  ignore_errors: true

- name: Build nginx config
  vars: 
    DomainName: "{{ lookup('community.general.passwordstore', 'digitalocean' + '/domains/ttc/bzweek', errors='ignore') }}"
  template:
    src: bzweek.conf.j2
    dest: "{{ nginx_config_path }}/bzweek.conf"
  notify:
    - restart php-fpm
    - restart nginx

- name: Configure nginx HTTPS through certbot
  expect:
    command: certbot
    responses:
      (.*)activate HTTPS for(.*): "\n"
      (.*)reinstall this existing certificate(.*): "1"
      (.*)Make all requests redirect to secure HTTPS(.*): "2"
  notify:
    - restart nginx
