---

- name: Set up pre-prequisites
  hosts: local
  roles:
    - role: prepare-local
      tags:
        - restore
        - personal
        - asslpl

- name: Set up services on homeserver
  hosts: homeserver-root
  vars_files:
          - config.yml
  roles:
    - role: setup-firefly
      tags:
        - personal
        - finance

    - role: setup-ainv
      tags:
        - asslpl

    - role: setup-vikunja
      tags:
        - personal
        - productivity

    - role: setup-nextcloud
      tags:
        - personal
        - productivity
        - media

    - role: coopdevs.certbot_nginx
      vars:
        domain_name: "{{ lookup('community.general.passwordstore', 'homeserver.setup/secrets/1/do_name', errors='ignore') }}.{{ lookup('community.general.passwordstore', 'homeserver.setup/secrets/1/do_base_domain', errors='ignore') }}"
        letsencrypt_email: rounakdatta12@gmail.com
        certbot_force_update: false
      tags:
        - security

    - role: setup-phpmyadmin
      tags:
        - asslpl

    - role: setup-nginx
      tags:
        - stitch

    - role: setup-jobs
      tags:
        - automation
